# permissions for end users to view goldpingers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: goldpinger-viewer-role
rules:
- apiGroups:
  - goldpinger.bloomberg.com
  resources:
  - goldpingers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - goldpinger.bloomberg.com
  resources:
  - goldpingers/status
  verbs:
  - get
